# Generated by Django 3.2.16 on 2023-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(max_length=250, unique=True)),
                ('duration', models.CharField(max_length=100)),
                ('fees', models.FloatField()),
            ],
        ),
    ]
