# Generated by Django 3.2.16 on 2023-08-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_collage_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=100, null=True)),
                ('semail', models.EmailField(max_length=254)),
                ('smobile', models.CharField(max_length=10)),
                ('saddress', models.CharField(max_length=255)),
                ('sdegree', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('due_amount', models.FloatField()),
                ('scourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courses')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.DeleteModel(
            name='Collage',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
