# Generated by Django 3.2.16 on 2023-08-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230821_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='collage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
