# Generated by Django 3.2.16 on 2023-08-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_addstudent_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='due_amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=300)),
                ('employeesid', models.IntegerField(unique=True)),
                ('teacheremail', models.CharField(max_length=200, unique=True)),
                ('teacherpassword', models.CharField(max_length=300)),
                ('teachermobile', models.IntegerField()),
                ('joindate', models.DateField(auto_now_add=True)),
                ('education', models.CharField(max_length=100)),
                ('workexp', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='teachers/')),
                ('gender', models.CharField(choices=[{'Male', 'M'}, {'F', 'Female'}, {'Other', 'O'}], max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addstudent')),
                ('teachercourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courses')),
            ],
        ),
    ]
