# Generated by Django 3.2.16 on 2023-08-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230822_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employeesid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
